import ScrollProgress from "@/components/ScrollProgress";
import ThemeProvider from "@/components/ThemeProvider";
import { ThemeSelector } from "@/components/ThemeSelector";
import { Toaster } from "@/components/ui/sonner";
import { routing } from "@/lib/i18n/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { Cairo, Inter, Sora, Tajawal } from "next/font/google";
import Head from "next/head";
import { notFound } from "next/navigation";
import "./globals.css";

const CairoFont = Cairo({
  variable: "--font-cairo-sans",
  subsets: ["latin"],
});
const SoraFont = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});
const TajawalFont = Tajawal({
  variable: "--font-Tajawal",
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);
  const dir = locale === "ar" ? "rtl" : "ltr";
  return (
    <html className="" lang={locale} dir={dir}>
      <body
        className={`${CairoFont.variable} ${InterFont.variable} ${TajawalFont.variable} antialiased font-Tajawal ${SoraFont.variable}`}
      >
        <Head>
          <meta name="apple-mobile-web-app-title" content="DevMaher" />
        </Head>
        <NextIntlClientProvider>
          <ThemeProvider>
            <ThemeSelector />
            {/* <LanguageSwitcher /> */}
            {children}
            <ScrollProgress />
            <Toaster richColors />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
